apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jayd-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-persistent
  volumeMode: Filesystem
