name: Build

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/jayd

jobs:
  build:
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.repository_owner.login }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          mask-password: true

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}
          build-args: --build-arg COMMIT_SHA=${{ github.sha }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}

  deploy:
    needs: build
    runs-on: self-hosted
    environment: wheatley

    steps:
      - uses: axatol/actions/rollout-kubernetes-deployment@release
        with:
          deployment-name: jayd-deployment
          namespace: jayd
          wait: true

      - uses: axatol/actions/create-new-relic-deployment@release
        with:
          name: jayd
          api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          deployment-type: ROLLING
