name: Build

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/jayd

jobs:
  check:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod

      - run: |
          make deps
          make vet

      - uses: actions/setup-node@v3
        with:
          cache: false
          node-version-file: .nvmrc

      - run: |
          npm install
          npm run lint

  build:
    needs: check
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: axatol/actions/assume-aws-role@release
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          mask-password: true

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}
          build-args: --build-arg COMMIT_SHA=${{ github.sha }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}

  deploy:
    needs: build
    runs-on: self-hosted
    environment: wheatley

    steps:
      - uses: axatol/actions/rollout-kubernetes-deployment@release
        with:
          deployment-name: jayd-deployment
          namespace: jayd
          wait: true

      - uses: axatol/actions/create-new-relic-deployment@release
        with:
          name: jayd
          api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          deployment-type: ROLLING
